pmgd/database/urls.py
from django.urls import path

from . import views

app_name = 'database'
urlpatterns = [
    path('',views.Home.as_view(),name="home"),
    path('Abrowse',views.Genome_browser.as_view(),name="genome_browser"),
    path('Tools',views.Tools.as_view(),name="tools"),
    path('Tutorial',views.Tutorial.as_view(),name="tutorial"),
    path('Upload',views.Upload.as_view(),name="upload"),
]

pmgd/pmgd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('pmgd/', include('database.urls')),
    path('admin/', admin.site.urls),
]

pmgd/database/models.py
from django.db import models

# Create your models here.

pmgd/database/views.py
from django.shortcuts import render_to_response
from django.views import View

# Create your views here.

class Home(View):
    def get(self,request):
        return render_to_response("database/index.html")

class Genome_browser(View):
    def get(self,request):
        return render_to_response("database/genome_browser.html")

class Tools(View):
    def get(self,request):
        return render_to_response("database/tools.html")

class Tutorial(View):
    def get(self,request):
        return render_to_response("database/tutorial.html")

class Upload(View):
    def get(self,request):
        return render_to_response("database/upload.html")

pmgd/database/templates/database/genome_browser.html
{% extends "database/base.html" %}

pmgd/database/templates/database/index.html
{% extends "database/base.html" %}

pmgd/database/templates/database/tools.html
{% extends "database/base.html" %}

pmgd/database/templates/database/tutorial.html
{% extends "database/base.html" %}

pmgd/database/templates/database/upload.html
{% extends "database/base.html" %}

pmgd/templates/database/base.html
<!DOCTYPE html>

<html lang="en">
<head>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'database/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css"/>
  <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!--enable hover dropdown which bootstrap don't support by default.-->
  <script src="{% static 'database/js/bootstrap-hover-dropdown.min.js' %}"></script>
  <title> plant mitochondrion genome database </title>
</head>
<body>
  <div class="row" id="logos">
    <img src="{% static 'database/images/logo.gif' %} "></img>
  </div>
  <!--navbar-->
  <div class="navbar navbar-inverse" role="navigation"><!--role attr enable its general usage-->
    <div class="nav navbar-nav">
      <ul class='nav nav-pills'>
        <li><a href="#" class="dorpdown" data-toggle="dropdown" data-hover="dropdown">Home</a>
          <ul class="dropdown-menu">
            <li><a href="#">About</a></li>
            <li><a href="#">What's new</a></li>
            <li><a href="#">Contact us</a></li>
          </ul>
        </li>
        <li><a href="{% url 'database:genome_browser' %}">Genome Browser</a></li>
        <li><a href="#" class="dropdown" data-toggle="dropdown" data-hover="dropdown">Tools</a>
          <ul class="dropdown-menu">
            <li><a href="#">tool1</a></li>
            <li><a href="#">blast</a></li>
            <li><a href="#">tool3</a></li>
          </ul>
        </li>
        <li><a href="{% url 'database:tutorial' %}">Tutorial</a></li>
        <li><a href="{% url 'database:upload' %}">upload</a></li>
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
      </ul>
    </div><!--/.nav navbar-nav -->
  </div><!--./navbar navbar-default -->
</body>
</html>